version: "3.5"

services:
  redis:
    image: "bitnami/redis:latest"
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=ocsen-hoc-code
    networks:
      - ocsen_network

networks:
  ocsen_network:
